### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by apexad**
Just `npm audit fix` to update dependencies.

### CODE REVIEW

**Comment by joshstrange** [comment]
@apexad I'm assuming that after I merge this I should bump to the next eufy-robovac version that I just released?

**Comment by apexad** [comment]
@joshstrange yes, please bump versions of this plugin (which I think will actually be 1.0.4) and eufy-robovac too.  I can also do it once we make me a collaborator.  Up to you.

**Comment by joshstrange** [comment]
@apexad This has been merged, I bumped the eufy-robovac the newest, and published this under 1.1.0. I'm working on adding you now

**Comment by apexad** [comment]
@joshstrange I just wanted to check with you to confirm if it is ok to add myself as an author of this plugin and node script in package.json?  I'm planning on doing a bunch of updates and just want some credit there for it, and it will help to redirect questions to me on Reddit/Github/Discord.

**Comment by MonsterEnergy-wtf** [comment]
What about doing the update first and then asking for credits?
btw: the fix for the current version was mine...

So I highly suggest to contribute first before "highjacking" this.

But this is just my oppinion.
I don't care. ;-)

**Comment by apexad** [comment]
@MonsterEnergy-wtf I apologize for accidentally deleting your comment.  Also, I greatly appreciate that you let us all know this plugin was still working.

However, there was already a built dist/index.js floating around.  It actually seems like the real issue was simply that when this project was last updated prior to my coming onto it that the /dist/ folder was not getting pushed to npm.

I've already made changes in the published v1.1.1 to correct this and already have a beta version on npm https://www.npmjs.com/package/homebridge-eufy-robovac (which I am sure @joshstrange was notified of) that I am testing with other changes (removing webpack and just using tsc (type script compiler) and also removing the IP address as a config option). Since this all looks good, as far as I can tell, I will actually be working on making the 'Find' button optional and adding a config.schema.json (for https://www.npmjs.com/package/homebridge-config-ui-x) before publishing an updated version very soon.  If @joshstrange responds prior to then, I will also make the author update which I believe will be well deserved.

So, with that in mind, I think it's fair to say I've already spent.a considerable amount of time on this project as well as it's underlying library https://github.com/joshstrange/eufy-robovac where similar changes have been made including a pushed beta.

**Comment by apexad** [comment]
@joshstrange @MonsterEnergy-wtf FYI, I pushed v1.2.0 of the plugin and 1.4.0 of the underlying eufy-robovac library. As I mentioned above, it does the following:
* Removes the need for webpack (uses the type script compiler)
* Remove option to use IP address (must use deviceId)
* Added `hideFindButton` config option
* Added config.schema.json (for use with homebridge-config-ui-x)

**Pull request merged**
